services:
  - type: web
    name: gems-api
    runtime: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: GEM_API_KEY
        sync: false
      - key: GEM_ID
        value: fcf6f88e78ea
      - key: GEM_PORT
        value: "8001"
      - key: CONVEX_URL
        sync: false
      - key: BROWSER_REFRESH
        value: "true"
